---
all:
  hosts:
    master100:
      ansible_host: 192.168.1.100
      ip: 192.168.1.100
      access_ip: 192.168.1.100
    master101:
      ansible_host: 192.168.1.101
      ip: 192.168.1.101
      access_ip: 192.168.1.101
    master102:
      ansible_host: 192.168.1.102
      ip: 192.168.1.102
      access_ip: 192.168.1.102
    worker103:
      ansible_host: 192.168.1.103
      ip: 192.168.1.103
      access_ip: 192.168.1.103
    worker104:
      ansible_host: 192.168.1.104
      ip: 192.168.1.104
      access_ip: 192.168.1.104
    worker105:
      ansible_host: 192.168.1.105
      ip: 192.168.1.105
      access_ip: 192.168.1.105
  children:
    kube_control_plane:
      hosts:
        master100:
        master101:
        master102:
    kube_node:
      hosts:
        worker103:
        worker104:
        worker105:
    etcd:
      hosts:
        master100:
        master101:
        master102:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
